### ISSUE TITLE
Pimatic-filter errors

### ISSUE THREAD

**Issue by edautz** [mwittig/pimatic-filter#1]
Today I installed Pimatic-filter 0.8.3 to filter some mysensors values.

But it fails on my system:
I got the following errors:

error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
22:43:42error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
22:43:11error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
22:36:26error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
22:32:52error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
22:31:39error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
22:25:10error [pimatic]: Error loading device MultiSensorWoonkamerLichtsterkteSensorFilter: Property 'getVochtigheid' of object #<SimpleTruncatedMeanFilter> is not a function
22:25:07error [pimatic]: Error loading device MultiSensorWoonkamerDrukFilter: Property 'getVochtigheid' of object #<SimpleTruncatedMeanFilter> is not a function

Config:

```
{
  "id": "MultiSensorWoonkamer",
  "name": "Multi Sensor Woonkamer",
  "class": "MySensorsMulti",
  "attributes": [
    {
      "name": "Vochtigheid",
      "nodeid": 9,
      "sensorid": 0,
      "type": "float",
      "acronym": "Vochtigheid: ",
      "unit": "%"
    },
    {
      "name": "Temperatuur",
      "nodeid": 9,
      "sensorid": 1,
      "type": "float",
      "acronym": "Temperatuur: ",
      "unit": "°C"
    },
    {
      "name": "Druk",
      "nodeid": 9,
      "sensorid": 2,
      "sensortype": 4,
      "type": "integer",
      "acronym": "Druk: ",
      "unit": "hPa"
    },
    {
      "name": "LichtsterkteSensor",
      "nodeid": 9,
      "sensorid": 3,
      "type": "integer",
      "acronym": "Lichtsterkte: ",
      "unit": "Lux"
    },
    {
      "name": "Voorspelling",
      "nodeid": 9,
      "sensorid": 2,
      "sensortype": 5,
      "type": "string",
      "acronym": "Voorspelling: "
    }
  ]
},
{
  "id": "MultiSensorWoonkamerVochtigheidFilter",
  "name": "Multi SensorWoonkamer Vochtigheid Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Vochtigheid",
    "expression": "$MultiSensorWoonkamer.Vochtigheid",
    "acronym": "Vochtigheid: ",
    "type": "number",
    "unit": "%"
  }
},
{
  "id": "MultiSensorWoonkamerTemperatuurFilter",
  "name": "Multi SensorWoonkamer Temperatuur Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Vochtigheid",
    "expression": "$MultiSensorWoonkamer.Temperatuur",
    "acronym": "Temperatuur: ",
    "type": "number",
    "unit": "°C"
  }
},
{
  "id": "MultiSensorWoonkamerDrukFilter",
  "name": "Multi SensorWoonkamer Druk Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Druk",
    "expression": "$MultiSensorWoonkamer.Temperatuur",
    "acronym": "Druk: ",
    "type": "number",
    "unit": "hPa"
  }
},
{
  "id": "MultiSensorWoonkamerLichtsterkteSensorFilter",
  "name": "Multi SensorWoonkamer LichtsterkteSensor Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Druk",
    "expression": "$MultiSensorWoonkamer.LichtsterkteSensor",
    "acronym": "Lichtsterkte: ",
    "type": "number",
    "unit": "Lux"
  }
},
```

I can't see any filter devices either.

However in the debuf of the filter plugin, processing is going on:

debug [pimatic-filter]: 19.9 [ 20, 19.9, 19.9, 19.9, 19.8 ] [ 19.9, 19.9, 19.9 ]
22:30:35debug [pimatic-filter]: 64.3 [ 64.3, 64.3, 64.3, 64.3, 64.3 ] [ 64.3, 64.3, 64.3 ]
22:30:35debug [pimatic-filter]: 19.9 [ 20, 19.9, 19.9, 19.9 ] [ 19.9, 19.9 ]
22:30:35debug [pimatic-filter]: 19.9 [ 20, 19.9, 19.9, 19.9 ] [ 19.9, 19.9 ]
22:30:35debug [pimatic-filter]: 64.3 [ 64.5, 64.3, 64.3, 64.3, 64.3 ] [ 64.3, 64.3, 64.3 ]
22:30:35debug [pimatic-filter]: 19.9 [ 20, 19.9, 19.9 ] [ 19.9 ]
22:30:35debug [pimatic-filter]: 19.9 [ 20, 19.9, 19.9 ] [ 19.9 ]
22:30:35debug [pimatic-filter]: 64.3 [ 64.5, 64.3, 64.3, 64.3 ] [ 64.3, 64.3 ]
22:30:35debug [pimatic-filter]: 64.3 [ 64.5, 64.3, 64.3 ] [ 64.3 ]
22:30:35debug [pimatic-filter]: 64.4 [ 64.5, 64.3 ] [ 64.5, 64.3 ]
22:30:35debug [pimatic-filter]: 19.95 [ 20, 19.9 ] [ 20, 19.9 ]
22:30:35debug [pimatic-filter]: 19.95 [ 20, 19.9 ] [ 20, 19.9 ]
22:30:33debug [pimatic-filter]: 2 [ 2 ] [ 2 ]
22:30:33debug [pimatic-filter]: 20 [ 20 ] [ 20 ]
22:30:33debug [pimatic-filter]: 20 [ 20 ] [ 20 ]
22:30:33debug [pimatic-filter]: 64.5 [ 64.5 ] [ 64.5 ]

Is my config incorrect?

Kind regards,

Edautz

**Comment by mwittig** [comment]
Thank you for reporting this issue. I'll try to improve the error handling for this case. I have not yet managed to reproduce the error, but I think it is due to a configuration error. As part of the log you should also see error messages like:

13:13:13.729 [pimatic] Error loading device <device id>: Invalid config of device  <device id>: 
13:13:13.729 [pimatic]>#/variables/0/type: Should have enum string,number, was: float

@edautz wrote

> Is my config incorrect?

You're using "integer" and "float" types as part of the configuration. I don't think these types are supported by pimatic. Please use "number" instead. This should hopefully resolve the issue.

**Comment by mwittig** [comment]
Published new release.  Please **re-open** if the issue remains.
