### ISSUE TITLE
Sparklines  are shown wheras default values are shown as false in device edit dialog.

### ISSUE THREAD

**Issue by Heizelmann** [mwittig/pimatic-filter#13]
Explicitly setting or hiding sparklines works as expected but when leaving unchecked the displaySparkline option the default value of button shows no but result is that sparklines are showed.

**Comment by mwittig** [comment]
Yes, that's a glitch in the matrix. The device editor does not seem to pick up the default to display the value, correctly. I am closing this issue as the device editor is common feature of the pimatic framework and not of the filter plugin. Feel free to create an issue at https://github.com/pimatic/pimatic
